<a href="https://colab.research.google.com/github/Rohit991371/Deep-Learning-with-PyTorch/blob/main/2_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
# !pip list

In [4]:
my_list = [[1,2,3,4],[4,5,6,7]]
my_list

[[1, 2, 3, 4], [4, 5, 6, 7]]

In [5]:
np1 = np.random.rand(3,6)
np1

array([[0.19148918, 0.69762256, 0.54379673, 0.38972687, 0.65354941,
        0.02443248],
       [0.28454451, 0.9326703 , 0.96244758, 0.80303245, 0.06696558,
        0.53499388],
       [0.0944542 , 0.11139437, 0.7501384 , 0.21916531, 0.69248999,
        0.40989096]])

In [6]:
np1.dtype

dtype('float64')

In [7]:
#Tensors
tensors_2d = torch.randn(3,6)
tensors_2d

tensor([[-0.1448,  0.2170,  1.3333,  1.4812,  1.8792,  0.6246],
        [ 0.5091, -0.0088,  0.5525, -0.6566,  1.5669, -1.1954],
        [ 0.2098, -1.2855,  0.5692, -1.3685, -1.3839,  0.0808]])

In [8]:
tensors_3d = torch.randn(3,6)
tensors_3d

tensor([[ 1.7540,  0.1987, -0.6669, -0.6236, -0.2178, -0.3265],
        [-0.2564,  0.2174,  0.8732,  0.3484,  0.4384, -0.3087],
        [ 0.5878,  1.5411,  0.3592, -0.7541,  0.9081,  0.0864]])

In [9]:
tensors_3d.dtype

torch.float32

In [10]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1915, 0.6976, 0.5438, 0.3897, 0.6535, 0.0244],
        [0.2845, 0.9327, 0.9624, 0.8030, 0.0670, 0.5350],
        [0.0945, 0.1114, 0.7501, 0.2192, 0.6925, 0.4099]], dtype=torch.float64)

In [11]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
#Reshape if we don't know the number of items using -1
my_torch1 = torch.arange(15)
my_torch1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
my_torch1 = my_torch1.reshape(3,-1)
my_torch1

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [15]:
my_torch3 = my_torch1.reshape(-1,3)
my_torch3

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [16]:
my_torch4 = torch.arange(10)
my_torch4


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch5 = my_torch4.view(2,5)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_torch6 = torch.arange(10)
my_torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_torch7 = my_torch6.reshape(2,5)
my_torch7

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
my_torch6[1] = 423
my_torch6

tensor([  0, 423,   2,   3,   4,   5,   6,   7,   8,   9])

In [21]:
my_torch7

tensor([[  0, 423,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [22]:
my_torch6[1]

tensor(423)

In [23]:
my_torch8 = my_torch6.reshape(5,2)
my_torch8

tensor([[  0, 423],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [24]:
my_torch8[:,1]

tensor([423,   3,   5,   7,   9])

In [25]:
my_torch8[:,1:]

tensor([[423],
        [  3],
        [  5],
        [  7],
        [  9]])

Tensor Math operation



In [26]:
tensor_a = torch.tensor([3,4,5,6])
tensor_b = torch.tensor([1,2,6,0])

In [27]:
tensor_a + tensor_b

tensor([ 4,  6, 11,  6])

In [29]:
torch.add(tensor_a, tensor_b)

tensor([ 4,  6, 11,  6])

In [30]:
tensor_a - tensor_b

tensor([ 2,  2, -1,  6])

In [32]:
torch.sub(tensor_a, tensor_b)

tensor([ 2,  2, -1,  6])

In [33]:
tensor_b / tensor_a

tensor([0.3333, 0.5000, 1.2000, 0.0000])

In [34]:
torch.div(tensor_b,tensor_a)

tensor([0.3333, 0.5000, 1.2000, 0.0000])

In [35]:
torch.remainder(tensor_b,tensor_a)

tensor([1, 2, 1, 0])

In [36]:
torch.pow(tensor_a,tensor_b)

tensor([    3,    16, 15625,     1])

In [37]:
tensor_a ** tensor_b

tensor([    3,    16, 15625,     1])

In [40]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 5,  8, 17,  6])

In [41]:
tensor_a


tensor([ 5,  8, 17,  6])